[project]
name = "simple-nodes"
version = "0.1.1"
description = "Simple Nodes: A set of nodes to simplify some tasks"
readme = "README.md"
requires-python = ">=3.10"
authors = [ { name = "xFennec777" } ]
license = { text = "MIT" }

[project.urls]
Repository = "https://github.com/JaredSartin/ComfyUI-SimpleNodes"

[build-system]
requires = ["setuptools>=61.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[tool.comfy]
PublisherId = "xfennec777" # TODO (fill in Publisher ID from Comfy Registry Website).
DisplayName = "Simple Nodes" # Display name for the Custom Node. Can be changed later.
# Icon = "https://example.com/icon.png" # SVG, PNG, JPG or GIF (MAX. 800x400px)
